apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-1.10
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: sample
        version: "1.10"
    spec:
      containers: 
        - name: sample
          image: sample:1.10
          ports:
            - name: http
              containerPort: 80
