apiVersion: v1
kind: Service
metadata: 
  name: sample
  labels: 
    name: sample
spec:
  ports:
    - name: http
      port: 7667
      targetPort: 7667
  selector: 
    name: nginx
    version: "1.10"
  type: LoadBalancer
